service: serverless-dynamic-workflows

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}
  logRetentionInDays: 14
  tracing:
    lambda: true
    apiGateway: true

  environment:
    CHUNK_SIZE: 100000
    POWERTOOLS_SERVICE_NAME: ${self:service}
    LOG_LEVEL: INFO
    DEPLOYMENT_REGION: ${self:provider.region}

  httpApi:
    cors: true
    authorizers:
      cognitoAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl: !Join
          - ''
          - - 'https://cognito-idp.'
            - ${self:provider.region}
            - '.amazonaws.com/'
            - !Ref CognitoUserPool
        audience:
          - !Ref CognitoUserPoolClient

  iam:
    role:
      statements: ${file(./lambda-permissions.yml):iamRoleStatements}

custom:
  flowsDir: flows
  plugins:
    packages: ${file(./config.json):plugins, []}
  flows: ${file(./deploy/load_flows.js)}  # Keep using original file

package:
  individually: true
  patterns:
    - "!node_modules/**"
    - "!.git/**"
    - "!.venv/**"
    - "!__pycache__/**"
    - "!.pytest_cache/**"
    - "!test/**"
    - "!tests/**"
    - "!*.pyc"
    - "!.DS_Store"
    - "!**.sample"
    - "!layer/**"

functions:
  getAuthConfig:
    handler: functions/base/auth/handler.get_config
    timeout: 30
    memorySize: 128
    package:
      patterns:
        - "functions/base/auth/**"
    layers:
      - {Ref: DependenciesLambdaLayer}
    environment:
      COGNITO_USER_POOL_ID: !Ref CognitoUserPool
      COGNITO_CLIENT_ID: !Ref CognitoUserPoolClient
      POWERTOOLS_METRICS_NAMESPACE: ${self:service}-auth
      API_USAGE_TABLE: ${self:service}-api-usage-${self:provider.stage}
    events:
      - httpApi:
          path: /auth/config
          method: GET

  verifyToken:
    handler: functions/base/auth/handler.verify_token
    timeout: 30
    memorySize: 128
    package:
      patterns:
        - "functions/base/auth/**"
    layers:
      - {Ref: DependenciesLambdaLayer}
    environment:
      POWERTOOLS_METRICS_NAMESPACE: ${self:service}-auth
      API_USAGE_TABLE: ${self:service}-api-usage-${self:provider.stage}
    events:
      - httpApi:
          path: /auth/verify
          method: GET
          authorizer:
            name: cognitoAuthorizer

  runFlow:
    handler: functions/base/run_flow/handler.handler
    timeout: 30
    memorySize: 256
    package:
      patterns:
        - "functions/base/run_flow/**"
    layers:
      - {Ref: DependenciesLambdaLayer}
    environment:
      POWERTOOLS_METRICS_NAMESPACE: ${self:service}-events-producer
      API_USAGE_TABLE: ${self:service}-api-usage-${self:provider.stage}
    events:
      - httpApi:
          path: /run/{flow_name}
          method: POST
          authorizer:
            name: cognitoAuthorizer

  listFlows:
      handler: functions/base/list_flows/handler.handler
      timeout: 30
      memorySize: 256
      package:
        patterns:
          - "functions/base/list_flows/**"
      layers:
        - {Ref: DependenciesLambdaLayer}
      environment:
        POWERTOOLS_METRICS_NAMESPACE: ${self:service}-flows
        API_USAGE_TABLE: ${self:service}-api-usage-${self:provider.stage}
      events:
        - httpApi:
            path: /flows
            method: GET
            authorizer:
              name: cognitoAuthorizer

  getFlowResult:
    handler: functions/base/get_flow_result/handler.handler
    timeout: 30
    memorySize: 256
    layers:
      - { Ref: DependenciesLambdaLayer }
    environment:
      API_USAGE_TABLE: ${self:service}-api-usage-${self:provider.stage}
    events:
      - httpApi:
          path: /run/{flow_name}/{execution_id}
          method: GET
          authorizer:
            name: cognitoAuthorizer

plugins:
  - ./deploy/serverless-dynamic-functions.js

layers:
  dependencies:
    path: layer
    description: Required dependencies for data frame processing
    compatibleRuntimes:
      - python3.9

resources:
  - ${file(./deploy/generate-step-functions.js)}
  - Resources:

      ApiUsageTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: ${self:service}-api-usage-${self:provider.stage}
          AttributeDefinitions:
            - AttributeName: userId
              AttributeType: S
            - AttributeName: yearMonth
              AttributeType: S
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: yearMonth
              KeyType: RANGE
          BillingMode: PAY_PER_REQUEST
          TimeToLiveSpecification:
            AttributeName: ttl
            Enabled: true

      CognitoUserPool:
        Type: AWS::Cognito::UserPool
        Properties:
          UserPoolName: ${self:service}-user-pool-${self:provider.stage}

      CognitoUserPoolClient:
        Type: AWS::Cognito::UserPoolClient
        Properties:
          UserPoolId: !Ref CognitoUserPool
          ClientName: ${self:service}-client-${self:provider.stage}
          GenerateSecret: false
          ExplicitAuthFlows:
            - ALLOW_USER_PASSWORD_AUTH
            - ALLOW_REFRESH_TOKEN_AUTH
            - ALLOW_USER_SRP_AUTH
          PreventUserExistenceErrors: ENABLED

    Outputs:
          UserPoolId:
            Value: !Ref CognitoUserPool
          UserPoolClientId:
            Value: !Ref CognitoUserPoolClient
          ApiUrl:
            Value:
              Fn::Sub:
                - https://${ApiId}.execute-api.${AWS::Region}.amazonaws.com/${Stage}
                - ApiId: !Ref HttpApi
                  Stage: ${self:provider.stage}